version: '3.7'

services:
  credit-card-api:
    container_name: credit-card-api
    restart: on-failure
    build:
      context: .
      dockerfile: ./apps/nestjs-rabbitmq-example/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: yarn start:api:dev
    depends_on:
      - rabbitmq

  consumer:
    restart: on-failure
    build:
      context: .
      dockerfile: ./apps/credit-card-consumer/Dockerfile
    volumes:
      - .:/usr/src/app
    command: yarn start:consumer:dev
    depends_on:
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 3
    
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - 5672:5672  
      - 15672:15672  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  

volumes:
  rabbitmq_data:
